### PR TITLE
Fixes #360: Can't deactivate an integration if it's k8s resources have been deleted.

### LINKED ISSUE #360: Can't deactivate an integration if it's k8s resources have been deleted.
```
2017-04-27 14:04:37.457  INFO [-,,,] 1 --- [pool-5-thread-1] c.r.i.c.i.IntegrationController          : Integration -KigCtl5t7sMOYx-bjqA : Desired status "Deactivated" != current status "Activated" --> calling status change handler
2017-04-27 14:04:37.458  INFO [-,,,] 1 --- [pool-4-thread-1] c.r.i.c.i.IntegrationController          : Integration -KigCtl5t7sMOYx-bjqA : Start processing integration with DeactivateHandler
2017-04-27 14:04:37.592 ERROR [-,,,] 1 --- [pool-4-thread-1] c.r.i.c.i.IntegrationController          : Error while processing integration status for integration -KigCtl5t7sMOYx-bjqA

io.fabric8.kubernetes.client.KubernetesClientException: Resource not found!
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:225) ~[kubernetes-client-2.2.13.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.edit(HasMetadataOperation.java:64) ~[kubernetes-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:69) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:48) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:67) ~[openshift-client-2.2.13.jar!/:na]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.edit(DeploymentConfigOperationsImpl.java:48) ~[openshift-client-2.2.13.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.lambda$scale$5(OpenShiftServiceImpl.java:90) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at io.fabric8.kubernetes.client.WithRequestCallable.call(WithRequestCallable.java:35) ~[kubernetes-client-2.2.13.jar!/:na]
	at com.redhat.ipaas.openshift.OpenShiftServiceImpl.scale(OpenShiftServiceImpl.java:89) ~[openshift-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.controllers.integration.online.DeactivateHandler.execute(DeactivateHandler.java:56) ~[controllers-0.1-SNAPSHOT.jar!/:na]
	at com.redhat.ipaas.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:159) ~[controllers-0.1-SNAPSHOT.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]

```

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

File: controllers/src/main/java/com/redhat/ipaas/controllers/integration/online/DeactivateHandler.java [hunk 1]
```diff
@@ -53,7 +54,13 @@ public StatusUpdate execute(Integration integration) {
             ? Integration.Status.Deactivated
             : Integration.Status.Pending;
 
-        openShiftService.scale(deployment);
+        try {
+            openShiftService.scale(deployment);
+        } catch (KubernetesClientException e) {
+            if( !"Resource not found!".equals(e.getMessage()) ) {
```
Comment (jimmidyson) [inline controllers/src/main/java/com/redhat/ipaas/controllers/integration/online/DeactivateHandler.java]: This is probably better checking the exception code for 404 I think.

Comment (rhuss) [inline controllers/src/main/java/com/redhat/ipaas/controllers/integration/online/DeactivateHandler.java]: yes, please change. never ever put business meaning on exception messages. Imagine the upstream developer improving the exception by including which kind of resource was not found. I as an upstream would never think of someone matching on my exception messages ...

**Comment by chirino-test** [comment]
@jimmidyson  switched to the 404 check.
